services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      AZURE_DOC_INTELLIGENCE_ENDPOINT: ${AZURE_DOC_INTELLIGENCE_ENDPOINT:?err}
      AZURE_DOC_INTELLIGENCE_KEY: ${AZURE_DOC_INTELLIGENCE_KEY:?err}
      MAX_WORKERS: ${MAX_WORKERS:-4}
      SURYA_ENABLED: "0"
    volumes:
      - /data/shared/database:/app/shared/database
      - /data/shared/processed:/app/shared/processed
      - /data/shared/uploads:/app/shared/uploads
      - /data/shared/temp:/app/shared/temp
    restart: unless-stopped
